/**
 * @fileoverview Language context for managing multi-language support
 * Provides language switching functionality and current language state
 */

'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  currentLanguage: string;
  changeLanguage: (language: string) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation resources
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.products': 'Products',
    'nav.orders': 'Orders',
    'nav.inventory': 'Inventory',
    'nav.wallet': 'Wallet',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.admin': 'Admin',
    'nav.seller': 'Seller',
    'nav.operator': 'Operator',
    // Authentication
    'auth.login': 'Sign In',
    'auth.register': 'Sign Up',
    'auth.logout': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.rememberMe': 'Remember Me',
    'auth.createAccount': 'Create Account',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.signInWith': 'Sign in with',
    'auth.signUpWith': 'Sign up with',
    'auth.twoFactorAuth': 'Two-Factor Authentication',
    'auth.enterCode': 'Enter verification code',
    'auth.welcome': 'Welcome back',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.accountType': 'Account Type',
    'auth.seller': 'Seller',
    'auth.buyer': 'Buyer',
    'auth.sellProducts': 'Sell products',
    'auth.buyProducts': 'Buy products',
    'auth.createAccountSubtitle': 'Create your account to get started',
    'auth.welcomeTitle': 'Welcome to Dropshipping',
    'auth.welcomeSubtitle': 'Join thousands of sellers and buyers in our marketplace. Start your journey today.',
    'auth.feature1': 'Easy product management',
    'auth.feature2': 'Multi-marketplace integration',
    'auth.feature3': 'Real-time analytics',
    'auth.feature4': '24/7 customer support',
    'auth.orContinueWith': 'Or continue with',
    'auth.signInWithGoogle': 'Sign in with Google',
    'auth.signInWithFacebook': 'Sign in with Facebook',
    'auth.signInWithEmail': 'Sign in with Email',
    'auth.creatingAccount': 'Creating Account...',
    'auth.forgotPasswordTitle': 'Forgot Password?',
    'auth.forgotPasswordSubtitle': 'No worries! Enter your email address and we\'ll send you a reset link.',
    'auth.resetPasswordSubtitle': 'Enter your email to receive reset instructions',
    'auth.emailAddress': 'Email Address',
    'auth.enterEmailAddress': 'Enter your email address',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.sendingResetLink': 'Sending Reset Link...',
    'auth.backToSignIn': 'Back to Sign In',
    'auth.goToHomepage': 'Go to Homepage',
    'auth.rememberPassword': 'Remember your password?',
        'auth.signInHere': 'Sign in here',
        'auth.signUpHere': 'Sign up here',
        'auth.signingIn': 'Signing In...',
        'auth.invalidCredentials': 'Invalid email or password',
        'auth.loginFailed': 'Login failed. Please try again.',
    'auth.emailSent': 'Email Sent!',
    'auth.emailSentDescription': 'We\'ve sent a password reset link to your email address. Please check your inbox and follow the instructions to reset your password.',
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.totalProducts': 'Total Products',
    'dashboard.activeUsers': 'Active Users',
    'dashboard.pendingTasks': 'Pending Tasks',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.topProducts': 'Top Products',
        'dashboard.alerts': 'Alerts',
        'dashboard.notifications': 'Notifications',
        'dashboard.lowStockAlert': 'Low stock alert for Product #123',
        'dashboard.paymentProcessed': 'Payment processed successfully',
        'dashboard.newCustomerRegistration': 'New customer registration',
        'dashboard.viewAll': 'View All',
        'dashboard.vsLastMonth': 'vs last month',
        'dashboard.newOrderReceived': 'New order received',
        'dashboard.newMessageFromCustomer': 'New message from customer',
        'dashboard.viewAllNotifications': 'View all notifications',
        'dashboard.welcomeSubtitle': 'Here\'s what\'s happening with your',
        'dashboard.time2hoursAgo': '2 hours ago',
        'dashboard.time4hoursAgo': '4 hours ago',
        'dashboard.time6hoursAgo': '6 hours ago',
        'dashboard.time8hoursAgo': '8 hours ago',
        'dashboard.time5minAgo': '5 min ago',
        'dashboard.time1hourAgo': '1 hour ago',
        'dashboard.time2minAgo': '2 min ago',
        'dashboard.time3hoursAgo': '3 hours ago',
        'dashboard.time5hoursAgo': '5 hours ago',
    // Products
    'products.title': 'Products',
    'products.addProduct': 'Add Product',
    'products.editProduct': 'Edit Product',
    'products.deleteProduct': 'Delete Product',
    'products.productName': 'Product Name',
    'products.description': 'Description',
    'products.price': 'Price',
    'products.stock': 'Stock',
    'products.category': 'Category',
    'products.sku': 'SKU',
    'products.status': 'Status',
    'products.active': 'Active',
    'products.inactive': 'Inactive',
    'products.outOfStock': 'Out of Stock',
    'products.lowStock': 'Low Stock',
    'products.inStock': 'In Stock',
    // Orders
    'orders.title': 'Orders',
    'orders.orderId': 'Order ID',
    'orders.customer': 'Customer',
    'orders.total': 'Total',
    'orders.status': 'Status',
    'orders.date': 'Date',
    'orders.created': 'Created',
    'orders.paid': 'Paid',
    'orders.separated': 'Separated',
    'orders.packed': 'Packed',
        'orders.shipped': 'Shipped',
        'orders.delivered': 'Delivered',
        'orders.returned': 'Returned',
        'orders.cancelled': 'Cancelled',
        'orders.processing': 'Processing',
    'orders.viewDetails': 'View Details',
    'orders.printLabel': 'Print Label',
    'orders.packingList': 'Packing List',
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.all': 'All',
    'common.none': 'None',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.thisWeek': 'This Week',
    'common.thisMonth': 'This Month',
        'common.thisYear': 'This Year',
        'common.account': 'account',
        // Home page
        'home.welcomeTo': 'Welcome to',
        'home.dropshipHub': 'Dropship Hub',
        'home.Dropshipping': 'Dropshipping',
        'home.subtitle': 'A comprehensive dropshipping and marketplace platform connecting sellers and buyers worldwide.',
        'home.getStarted': 'Get Started',
        'home.forSellers': 'For Sellers',
        'home.sellersDescription': 'List your products and reach customers worldwide',
        'home.easyProductManagement': 'Easy product management',
        'home.orderTracking': 'Order tracking',
        'home.analyticsDashboard': 'Analytics dashboard',
        'home.securePayments': 'Secure payments',
        'home.multiTenantInventory': 'Multi-tenant inventory management',
        'home.realTimeOrderTracking': 'Real-time order tracking',
        'home.automatedAlertsReporting': 'Automated alerts & reporting',
        'home.forBuyers': 'For Buyers',
        'home.buyersDescription': 'Discover and purchase products from verified sellers',
        'home.wideProductSelection': 'Wide product selection',
        'home.secureCheckout': 'Secure checkout',
        'home.orderHistory': 'Order history',
        'home.customerSupport': 'Customer support',
        'home.securePlatform': 'Secure Platform',
        'home.securePlatformDescription': 'Built with security and reliability in mind',
        'home.jwtAuthentication': 'JWT authentication',
        'home.dataEncryption': 'Data encryption',
        'home.monitoring247': '24/7 monitoring',
        'home.trustedByThousands': 'Trusted by Thousands',
        'home.joinCommunity': 'Join our growing community of sellers and buyers',
        'home.activeUsers': 'Active Users',
        'home.productsListed': 'Products Listed',
        'home.totalSales': 'Total Sales',
        'home.uptime': 'Uptime',
        'home.completeDropshippingSolution': 'Complete Dropshipping Solution',
        'home.theCompleteDropshippingSolution': 'The Complete Dropshipping Solution',
        'home.connectMarketplacesDescription': 'Connect with multiple marketplaces (Shopee, Mercado Livre, TikTok Shop, Amazon, etc.), automate your order management, and streamline your entire business operation.',
        'home.multiMarketplace': 'Multi-Marketplace',
        'home.scalable': 'Scalable',
        // Section headers
        'home.connectToLeadingMarketplaces': 'Connect to Leading Marketplaces',
        'home.automatedOrderManagement': 'Automated Order Management',
        'home.completeFinancialControl': 'Complete Financial Control',
        'home.launchYourBrandedPlatform': 'Launch Your Branded Platform',
        'home.plansAndSubscriptions': 'Plans and Subscriptions',
        'home.whyChooseDropshipHub': 'Why Choose Dropship Hub?',
        'home.readyToScaleYour': 'Ready to Scale Your',
        'home.dropshippingBusiness': 'Dropshipping Business?',
        // Marketplace names
        'home.shopee': 'Shopee',
        'home.mercadoLivre': 'Mercado Livre',
        'home.amazon': 'Amazon',
        'home.tikTokShop': 'TikTok Shop',
        'home.kwaiShop': 'Kwai Shop',
        'home.magalu': 'Magalu',
        // Order flow steps
        'home.orderReceived': 'Order Received',
        'home.autoInventorySync': 'Auto Inventory Sync',
        'home.stockManagement': 'Stock Management',
        'home.instantInvoicing': 'Instant Invoicing',
        'home.fastShipment': 'Fast Shipment',
        // Feature highlights
        'home.lightningFast': 'Lightning Fast',
        'home.fullyAutomated': 'Fully Automated',
        'home.errorFree': 'Error-Free',
        // Digital wallet
        'home.myWallet': 'My Wallet',
        'home.recentTransactions': 'Recent Transactions',
        'home.trackYourEarnings': 'Track Your Earnings',
        'home.securePaymentProcessing': 'Secure Payment Processing',
        'home.instantWithdrawals': 'Instant Withdrawals',
        'home.supportedPaymentMethods': 'Supported Payment Methods',
        // Whitelabel features
        'home.customDomainBranding': 'Custom Domain & Branding',
        'home.completeVisualControl': 'Complete Visual Control',
        'home.whiteLabeledPortal': 'White-Labeled Portal',
        'home.unlimitedScalability': 'Unlimited Scalability',
        'home.whatsIncluded': "What's Included",
        'home.yourBrand': 'Your Brand',
        // Plans
        'home.free': 'Free',
        'home.basic': 'Basic',
        'home.pro': 'Pro',
        'home.enterprise': 'Enterprise',
        'home.flexiblePaymentOptions': 'Flexible Payment Options',
        'home.creditCards': 'Credit Cards',
        'home.pix': 'PIX',
        'home.boleto': 'Boleto',
        // Footer
        'home.ourServices': 'OUR SERVICES',
        'home.gettingStarted': 'GETTING STARTED',
        'home.aboutUs': 'ABOUT US',
        'home.contactUs': 'CONTACT US',
        // Marketplace descriptions
        'home.seamlessIntegration': 'Seamless integration with all major e-commerce platforms',
        'home.realTimeStockSync': 'Real-time stock syncing',
        'home.easyProductPublishing': 'Easy product publishing',
        'home.orderManagementAutomation': 'Order management automation',
        'home.globalReachAutomatedFulfillment': 'Global reach with automated fulfillment',
        'home.socialCommerceMadeEasy': 'Social commerce made easy',
        'home.quickProductPublishingSalesTracking': 'Quick product publishing & sales tracking',
        'home.brazilianMarketLeaderIntegration': 'Brazilian market leader integration',
        // Badge texts
        'home.automated': 'Automated',
        'home.secure': 'Secure',
        // Additional texts
        'home.signIn': 'Sign In',
        'home.getStartedFree': 'Get Started Free',
        'home.perfectForGettingStarted': 'Perfect for getting started',
        'home.popular': 'Popular',
        'home.perMonth': 'per month',
        'home.everythingYouNeedToSucceed': 'Everything you need to succeed in dropshipping',
        'home.joinThousandsOfSuccessfulEntrepreneurs': 'Join thousands of successful entrepreneurs who are already using our platform',
        'home.alreadyHaveAnAccount': 'Already have an account?',
        // Additional marketplace and workflow text
        'home.automatedWorkflow': 'Automated Workflow',
        'home.fromOrderReceivedToShipment': 'From order received to shipment - fully automated in seconds with zero errors',
        'home.automatedInRealTime': 'Automated in real-time with zero manual intervention. Our intelligent system handles everything seamlessly.',
        'home.lessThan2s': '< 2s',
        'home.successRate': '99.9% Success',
        'home.processingTime': '< 5s Processing Time',
        'home.accuracyRate': '99.9% Accuracy Rate',
        'home.alwaysActive': '24/7 Always Active',
        'home.ordersProcessedInstantly': 'Orders processed instantly with real-time inventory sync across all marketplaces',
        'home.zeroManualWork': 'Zero manual work - from order capture to invoice generation, everything runs automatically',
        'home.aiPoweredValidation': 'AI-powered validation ensures 99.9% accuracy with automatic error detection and recovery',
        'home.trackEarningsManageTransactions': 'Track earnings, manage transactions, and process instant withdrawals - all in one place',
        'home.totalBalance': 'Total Balance',
        'home.thisMonth': 'this month',
        'home.paymentReceived': 'Payment Received',
        'home.order': 'Order',
        'home.today': 'Today',
        'home.yesterday': 'Yesterday',
        'home.realTimeBalance': 'Real-time balance',
        'home.realTimeRevenueTracking': 'Real-time revenue tracking with detailed analytics, automated reports, and financial insights to help you grow your business.',
        'home.bankLevelEncryption': 'Bank-level encryption, fraud protection, and compliance with international security standards keep your money safe.',
        'home.accessFundsAnytime': 'Access your funds anytime with automated payouts. Integration with Mercado Pago, PIX, and major payment gateways.',
        // Additional missing translations
        'home.hoverToPauseRotation': 'Hover to pause rotation',
        'home.marketplaceIntegration': 'Marketplace Integration',
        'home.bankTransfer': 'Bank Transfer',
        'home.withdrawal': 'Withdrawal',
        'home.daysAgo': 'days ago',
        // Whitelabel Solution
        'home.completeWhitelabelSolution': 'Complete whitelabel solution with custom domains, branding, and unlimited scalability',
        'home.dropshipPlatform': 'Dropship Platform',
        'home.customColorScheme': 'Custom Color Scheme',
        'home.useYourOwnDomain': 'Use your own domain name and create a unique brand identity that resonates with your customers.',
        'home.customizeColorsLogos': 'Customize colors, logos, fonts, and layouts to match your brand perfectly across all pages.',
        'home.customersSeeOnlyYourBrand': 'Your customers see only your brand - no third-party branding or references anywhere.',
        'home.growWithoutLimits': 'Grow without limits - add unlimited products, users, and marketplaces as you scale.',
        'home.customLogoFavicon': 'Custom logo & favicon',
        'home.customColorSchemes': 'Custom color schemes',
        'home.customDomainSetup': 'Custom domain setup',
        'home.emailTemplatesWithBranding': 'Email templates with branding',
        'home.fullyCustomizableYourBrandYourRules': '100% Customizable • Your Brand • Your Rules',
        // Plans and Subscriptions
        'home.flexiblePricingPlans': 'Flexible pricing plans designed to scale with your dropshipping business',
        'home.activeSKUs': 'Active SKUs',
        'home.ordersPerMonth': 'Orders/month',
        'home.marketplaces': 'Marketplaces',
        'home.basicSupport': 'Basic Support',
        'home.emailSupport': 'Email Support',
        'home.basicReports': 'Basic Reports',
        'home.prioritySupport': 'Priority Support',
        'home.advancedReports': 'Advanced Reports',
        'home.apiAccess': 'API Access',
        'home.unlimitedSKUs': 'Unlimited SKUs',
        'home.unlimitedOrders': 'Unlimited Orders',
        'home.unlimitedMarketplaces': 'Unlimited Marketplaces',
        'home.allMarketplaces': 'All Marketplaces',
        'home.support24_7': '24/7 Support',
        'home.customReports': 'Custom Reports',
        'home.dedicatedManager': 'Dedicated Manager',
        'home.startFree': 'Start Free',
        'home.startBasicPlan': 'Start Basic Plan',
        'home.goPro': 'Go Pro',
        'home.contactSales': 'Contact Sales',
        'home.custom': 'Custom',
        // Payment Options
        'home.visaMastercardAmericanExpress': 'Visa, Mastercard, American Express',
        'home.instantBrazilianPayments': 'Instant Brazilian payments',
        'home.bankSlipPayments': 'Bank slip payments',
        'home.automaticBilling': 'Automatic billing',
        'home.retryOnFailure': 'Retry on failure',
        'home.webhookIntegration': 'Webhook integration',
        'home.autoUpgradeOptions': 'Auto-upgrade options',
        
        // Admin Dashboard
        'admin.welcomeBack': 'Welcome Back',
        'admin.dashboard': 'Admin Dashboard',
        'admin.loadingDashboard': 'Loading Admin Dashboard...',
        'admin.userManagement': 'User Management',
        'admin.allUsers': 'All Users',
        'admin.addNewUser': 'Add New User',
        'admin.searchUsers': 'Search users by name or email...',
        'admin.loadingUsers': 'Loading Users...',
        'admin.backToAdmin': 'Back to Admin Dashboard',
        'admin.enterFirstName': 'Enter first name',
        'admin.enterLastName': 'Enter last name',
        'admin.enterEmail': 'Enter email address',
        'admin.enterPassword': 'Enter password',
        'admin.confirmPassword': 'Confirm password',
        'admin.permissions': 'Permissions',
        'admin.loadingPermissions': 'Loading Permissions...',
        'admin.searchPermissions': 'Search permissions...',
        'admin.allCategories': 'All Categories',
        'admin.searchModules': 'Search modules, suppliers, orders...',
        'admin.searchSuppliers': 'Search suppliers...',
        'admin.searchProducts': 'Search products...',
        
        // Admin Sidebar and Navigation
        'admin.controlPanel': 'Admin Control Panel',
        'admin.platformManagement': 'Platform Management',
        'admin.overview': 'Overview',
        'admin.multiTenantSuppliers': 'Multi-Tenant Suppliers',
        'admin.supplierManagement': 'Supplier Management',
        'admin.productManagement': 'Product Management',
        'admin.orderManagement': 'Order Management',
        'admin.financialManagement': 'Financial Management',
        'admin.analytics': 'Analytics',
        'admin.settings': 'Settings',
        'admin.notifications': 'Notifications',
        'admin.recentActivity': 'Recent Activity',
        'admin.quickActions': 'Quick Actions',
        'admin.systemSettings': 'System Settings',
        
        // User Roles
        'admin.admins': 'Admins',
        'admin.operators': 'Operators',
        'admin.suppliers': 'Suppliers',
        'admin.sellers': 'Sellers',
        
        // Admin Descriptions
        'admin.manageAllUsers': 'Manage all platform users and their permissions',
        'admin.configureRoleBasedAccess': 'Configure role-based access control permissions',
        'admin.saveChanges': 'Save Changes',
        
        // Admin Stats and Data
        'admin.totalSuppliers': 'Total Suppliers',
        'admin.activeSuppliers': 'Active Suppliers',
        'admin.newSupplierOnboarded': 'New supplier "TechSupply Pro" onboarded successfully',
        'admin.batchOrdersProcessed': 'Batch of 47 orders processed automatically',
        'admin.commissionPayoutCompleted': '$12,450 commission payout completed',
        'admin.lowInventoryAlert': 'Low inventory alert for 5 products',
        'admin.apiSyncCompleted': 'Mercado Livre API sync completed',
        'admin.minAgo': 'min ago',
        
        // Admin Categories
        'admin.financial': 'Financial',
        'admin.reportsAnalytics': 'Reports & Analytics',
        'admin.allSuppliers': 'All Suppliers',
        
        // Admin Actions
        'admin.viewAnalytics': 'View Analytics',
        'admin.viewFinancialData': 'View Financial Data',
        'admin.viewSettings': 'View Settings',
        'admin.editSettings': 'Edit Settings',
        'admin.configureSettings': 'Configure Settings',
        // Key Benefits
        'home.connectWithMultipleMarketplacesSellEverywhere': 'Connect with multiple marketplaces and sell everywhere',
        'home.focusOnGrowingBusinessHandleLogistics': 'Focus on growing your business while we handle logistics',
        'home.runYourOwnBrandedPlatformScalability': 'Run your own branded platform for scalability',
        'home.seamlessFinancialTransactionsIntegratedGateways': 'Seamless financial transactions with integrated payment gateways',
        'home.alwaysUpToDateAcrossAllPlatforms': 'Always up-to-date, across all platforms',
        // Footer
        'home.dropshipHubForMe': 'Dropship Hub For Me',
        'home.dropshipHubForBusiness': 'Dropship Hub For Business',
        'home.howItWorks': 'How It Works',
        'home.pricingAndPlans': 'Pricing & Plans',
        'home.faqs': 'FAQs',
        'home.shippingMethods': 'Shipping Methods',
        'home.whatCanISell': 'What Can I Sell?',
        'home.whatIsDropshipHub': 'What Is Dropship Hub',
        'home.warehouseLocations': 'Warehouse Locations',
        'home.blog': 'Blog',
        'home.news': 'News',
        'home.customerReviews': 'Customer Reviews',
        'home.affiliateProgram': 'Affiliate Program',
        'home.directSellers': 'Direct Sellers',
        'home.usUnlocked': 'US Unlocked',
        'home.contactUsLink': 'Contact Us',
        'home.liveChatPST': 'Live chat (PST Time Zone):',
        'home.weekdaysHours': 'Weekdays: 9AM to 5PM',
        'home.weekendsClosed': 'Weekends: Closed',
        // CTA Section
        'home.noCreditCardRequired': 'No credit card required',
        'home.freeForeverPlan': 'Free forever plan',
        'home.setupIn5Minutes': 'Setup in 5 minutes',
        // Additional missing translations
        'home.multiChannelIntegration': 'Multi-Channel Integration',
        'home.automatedOrderFulfillment': 'Automated Order Fulfillment',
        'home.whitelabelSolution': 'Whitelabel Solution',
        'home.digitalWallet': 'Digital Wallet',
        'home.realTimeDataSyncing': 'Real-Time Data Syncing',
        'home.mercadoPago': 'Mercado Pago',
        'home.creditCard': 'Credit Card',
        'home.allRightsReserved': 'All rights reserved',
        'home.privacyPolicy': 'Privacy Policy',
        'home.termsOfService': 'Terms of Service',
        'home.signUpNowItsFree': 'Sign Up Now - It\'s Free!'
  },
  pt: {
    // Navigation
    'nav.dashboard': 'Painel',
    'nav.products': 'Produtos',
    'nav.orders': 'Pedidos',
    'nav.inventory': 'Estoque',
    'nav.wallet': 'Carteira',
    'nav.settings': 'Configurações',
    'nav.profile': 'Perfil',
    'nav.logout': 'Sair',
    'nav.admin': 'Admin',
    'nav.seller': 'Vendedor',
    'nav.operator': 'Operador',
    // Authentication
    'auth.login': 'Entrar',
    'auth.register': 'Cadastrar',
    'auth.logout': 'Sair',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.forgotPassword': 'Esqueceu a senha?',
    'auth.resetPassword': 'Redefinir Senha',
    'auth.rememberMe': 'Lembrar de mim',
    'auth.createAccount': 'Criar Conta',
    'auth.alreadyHaveAccount': 'Já tem uma conta?',
    'auth.dontHaveAccount': 'Não tem uma conta?',
    'auth.signInWith': 'Entrar com',
    'auth.signUpWith': 'Cadastrar com',
    'auth.twoFactorAuth': 'Autenticação de Dois Fatores',
    'auth.enterCode': 'Digite o código de verificação',
    'auth.welcome': 'Bem-vindo de volta',
    'auth.firstName': 'Primeiro Nome',
    'auth.lastName': 'Sobrenome',
    'auth.accountType': 'Tipo de Conta',
    'auth.seller': 'Vendedor',
    'auth.buyer': 'Comprador',
    'auth.sellProducts': 'Vender produtos',
    'auth.buyProducts': 'Comprar produtos',
    'auth.createAccountSubtitle': 'Crie sua conta para começar',
    'auth.welcomeTitle': 'Bem-vindo ao Dropshipping',
    'auth.welcomeSubtitle': 'Junte-se a milhares de vendedores e compradores em nosso marketplace. Comece sua jornada hoje.',
    'auth.feature1': 'Gerenciamento fácil de produtos',
    'auth.feature2': 'Integração multi-marketplace',
    'auth.feature3': 'Análises em tempo real',
    'auth.feature4': 'Suporte ao cliente 24/7',
    'auth.orContinueWith': 'Ou continue com',
    'auth.signInWithGoogle': 'Entrar com Google',
    'auth.signInWithFacebook': 'Entrar com Facebook',
    'auth.signInWithEmail': 'Entrar com E-mail',
    'auth.creatingAccount': 'Criando Conta...',
    'auth.forgotPasswordTitle': 'Esqueceu a Senha?',
    'auth.forgotPasswordSubtitle': 'Sem problemas! Digite seu endereço de e-mail e enviaremos um link de redefinição.',
    'auth.resetPasswordSubtitle': 'Digite seu e-mail para receber instruções de redefinição',
    'auth.emailAddress': 'Endereço de E-mail',
    'auth.enterEmailAddress': 'Digite seu endereço de e-mail',
    'auth.sendResetLink': 'Enviar Link de Redefinição',
    'auth.sendingResetLink': 'Enviando Link de Redefinição...',
    'auth.backToSignIn': 'Voltar para Entrar',
    'auth.goToHomepage': 'Ir para Página Inicial',
    'auth.rememberPassword': 'Lembrou da sua senha?',
        'auth.signInHere': 'Entre aqui',
        'auth.signUpHere': 'Cadastre-se aqui',
        'auth.signingIn': 'Entrando...',
        'auth.invalidCredentials': 'E-mail ou senha inválidos',
        'auth.loginFailed': 'Falha no login. Por favor, tente novamente.',
    'auth.emailSent': 'E-mail Enviado!',
    'auth.emailSentDescription': 'Enviamos um link de redefinição de senha para o seu endereço de e-mail. Verifique sua caixa de entrada e siga as instruções para redefinir sua senha.',
    // Dashboard
    'dashboard.welcome': 'Bem-vindo de volta',
    'dashboard.totalOrders': 'Total de Pedidos',
    'dashboard.totalRevenue': 'Receita Total',
    'dashboard.totalProducts': 'Total de Produtos',
    'dashboard.activeUsers': 'Usuários Ativos',
    'dashboard.pendingTasks': 'Tarefas Pendentes',
    'dashboard.recentOrders': 'Pedidos Recentes',
    'dashboard.topProducts': 'Produtos em Destaque',
        'dashboard.alerts': 'Alertas',
        'dashboard.notifications': 'Notificações',
        'dashboard.lowStockAlert': 'Alerta de estoque baixo para Produto #123',
        'dashboard.paymentProcessed': 'Pagamento processado com sucesso',
        'dashboard.newCustomerRegistration': 'Novo cadastro de cliente',
        'dashboard.viewAll': 'Ver Todos',
        'dashboard.vsLastMonth': 'vs mês passado',
        'dashboard.newOrderReceived': 'Novo pedido recebido',
        'dashboard.newMessageFromCustomer': 'Nova mensagem do cliente',
        'dashboard.viewAllNotifications': 'Ver todas as notificações',
        'dashboard.welcomeSubtitle': 'Aqui está o que está acontecendo com sua',
        'dashboard.time2hoursAgo': '2 horas atrás',
        'dashboard.time4hoursAgo': '4 horas atrás',
        'dashboard.time6hoursAgo': '6 horas atrás',
        'dashboard.time8hoursAgo': '8 horas atrás',
        'dashboard.time5minAgo': '5 min atrás',
        'dashboard.time1hourAgo': '1 hora atrás',
        'dashboard.time2minAgo': '2 min atrás',
        'dashboard.time3hoursAgo': '3 horas atrás',
        'dashboard.time5hoursAgo': '5 horas atrás',
    // Products
    'products.title': 'Produtos',
    'products.addProduct': 'Adicionar Produto',
    'products.editProduct': 'Editar Produto',
    'products.deleteProduct': 'Excluir Produto',
    'products.productName': 'Nome do Produto',
    'products.description': 'Descrição',
    'products.price': 'Preço',
    'products.stock': 'Estoque',
    'products.category': 'Categoria',
    'products.sku': 'SKU',
    'products.status': 'Status',
    'products.active': 'Ativo',
    'products.inactive': 'Inativo',
    'products.outOfStock': 'Sem Estoque',
    'products.lowStock': 'Estoque Baixo',
    'products.inStock': 'Em Estoque',
    // Orders
    'orders.title': 'Pedidos',
    'orders.orderId': 'ID do Pedido',
    'orders.customer': 'Cliente',
    'orders.total': 'Total',
    'orders.status': 'Status',
    'orders.date': 'Data',
    'orders.created': 'Criado',
    'orders.paid': 'Pago',
    'orders.separated': 'Separado',
    'orders.packed': 'Empacotado',
        'orders.shipped': 'Enviado',
        'orders.delivered': 'Entregue',
        'orders.returned': 'Devolvido',
        'orders.cancelled': 'Cancelado',
        'orders.processing': 'Processando',
    'orders.viewDetails': 'Ver Detalhes',
    'orders.printLabel': 'Imprimir Etiqueta',
    'orders.packingList': 'Lista de Embalagem',
    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.view': 'Visualizar',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.warning': 'Aviso',
    'common.info': 'Informação',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.confirm': 'Confirmar',
    'common.close': 'Fechar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.submit': 'Enviar',
    'common.reset': 'Resetar',
    'common.clear': 'Limpar',
    'common.select': 'Selecionar',
    'common.all': 'Todos',
    'common.none': 'Nenhum',
    'common.today': 'Hoje',
    'common.yesterday': 'Ontem',
    'common.thisWeek': 'Esta Semana',
    'common.thisMonth': 'Este Mês',
        'common.thisYear': 'Este Ano',
        'common.account': 'conta',
        // Home page
        'home.welcomeTo': 'Bem-vindo ao',
        'home.dropshipHub': 'Dropship Hub',
        'home.Dropshipping': 'Dropshipping',
        'home.subtitle': 'Uma plataforma abrangente de dropshipping e marketplace conectando vendedores e compradores em todo o mundo.',
        'home.getStarted': 'Começar',
        'home.forSellers': 'Para Vendedores',
        'home.sellersDescription': 'Liste seus produtos e alcance clientes em todo o mundo',
        'home.easyProductManagement': 'Gerenciamento fácil de produtos',
        'home.orderTracking': 'Rastreamento de pedidos',
        'home.analyticsDashboard': 'Painel de análises',
        'home.securePayments': 'Pagamentos seguros',
        'home.multiTenantInventory': 'Gerenciamento de estoque multi-inquilino',
        'home.realTimeOrderTracking': 'Rastreamento de pedidos em tempo real',
        'home.automatedAlertsReporting': 'Alertas e relatórios automatizados',
        'home.forBuyers': 'Para Compradores',
        'home.buyersDescription': 'Descubra e compre produtos de vendedores verificados',
        'home.wideProductSelection': 'Ampla seleção de produtos',
        'home.secureCheckout': 'Checkout seguro',
        'home.orderHistory': 'Histórico de pedidos',
        'home.customerSupport': 'Suporte ao cliente',
        'home.securePlatform': 'Plataforma Segura',
        'home.securePlatformDescription': 'Construída com segurança e confiabilidade em mente',
        'home.jwtAuthentication': 'Autenticação JWT',
        'home.dataEncryption': 'Criptografia de dados',
        'home.monitoring247': 'Monitoramento 24/7',
        'home.trustedByThousands': 'Confiado por Milhares',
        'home.joinCommunity': 'Junte-se à nossa crescente comunidade de vendedores e compradores',
        'home.activeUsers': 'Usuários Ativos',
        'home.productsListed': 'Produtos Listados',
        'home.totalSales': 'Vendas Totais',
        'home.uptime': 'Tempo de Atividade',
        'home.completeDropshippingSolution': 'Solução Completa de Dropshipping',
        'home.theCompleteDropshippingSolution': 'A Solução Completa de Dropshipping',
        'home.connectMarketplacesDescription': 'Conecte-se com vários marketplaces (Shopee, Mercado Livre, TikTok Shop, Amazon, etc.), automatize seu gerenciamento de pedidos e simplifique toda sua operação de negócios.',
        'home.multiMarketplace': 'Multi-Marketplace',
        'home.scalable': 'Escalável',
        // Section headers
        'home.connectToLeadingMarketplaces': 'Conecte-se aos Principais Marketplaces',
        'home.automatedOrderManagement': 'Gerenciamento Automatizado de Pedidos',
        'home.completeFinancialControl': 'Controle Financeiro Completo',
        'home.launchYourBrandedPlatform': 'Lance Sua Plataforma Marcada',
        'home.plansAndSubscriptions': 'Planos e Assinaturas',
        'home.whyChooseDropshipHub': 'Por que Escolher o Dropship Hub?',
        'home.readyToScaleYour': 'Pronto para Escalar Seu',
        'home.dropshippingBusiness': 'Negócio de Dropshipping?',
        // Marketplace names
        'home.shopee': 'Shopee',
        'home.mercadoLivre': 'Mercado Livre',
        'home.amazon': 'Amazon',
        'home.tikTokShop': 'TikTok Shop',
        'home.kwaiShop': 'Kwai Shop',
        'home.magalu': 'Magalu',
        // Order flow steps
        'home.orderReceived': 'Pedido Recebido',
        'home.autoInventorySync': 'Sincronização Automática de Estoque',
        'home.stockManagement': 'Gerenciamento de Estoque',
        'home.instantInvoicing': 'Faturamento Instantâneo',
        'home.fastShipment': 'Envio Rápido',
        // Feature highlights
        'home.lightningFast': 'Velocidade da Luz',
        'home.fullyAutomated': 'Totalmente Automatizado',
        'home.errorFree': 'Sem Erros',
        // Digital wallet
        'home.myWallet': 'Minha Carteira',
        'home.recentTransactions': 'Transações Recentes',
        'home.trackYourEarnings': 'Acompanhe Seus Ganhos',
        'home.securePaymentProcessing': 'Processamento de Pagamento Seguro',
        'home.instantWithdrawals': 'Saques Instantâneos',
        'home.supportedPaymentMethods': 'Métodos de Pagamento Suportados',
        // Whitelabel features
        'home.customDomainBranding': 'Domínio Personalizado e Marca',
        'home.completeVisualControl': 'Controle Visual Completo',
        'home.whiteLabeledPortal': 'Portal White-Label',
        'home.unlimitedScalability': 'Escalabilidade Ilimitada',
        'home.whatsIncluded': 'O que está Incluído',
        'home.yourBrand': 'Sua Marca',
        // Plans
        'home.free': 'Gratuito',
        'home.basic': 'Básico',
        'home.pro': 'Pro',
        'home.enterprise': 'Empresarial',
        'home.flexiblePaymentOptions': 'Opções de Pagamento Flexíveis',
        'home.creditCards': 'Cartões de Crédito',
        'home.pix': 'PIX',
        'home.boleto': 'Boleto',
        // Footer
        'home.ourServices': 'NOSSOS SERVIÇOS',
        'home.gettingStarted': 'COMO COMEÇAR',
        'home.aboutUs': 'SOBRE NÓS',
        'home.contactUs': 'CONTATO',
        // Marketplace descriptions
        'home.seamlessIntegration': 'Integração perfeita com todas as principais plataformas de e-commerce',
        'home.realTimeStockSync': 'Sincronização de estoque em tempo real',
        'home.easyProductPublishing': 'Publicação fácil de produtos',
        'home.orderManagementAutomation': 'Automação de gerenciamento de pedidos',
        'home.globalReachAutomatedFulfillment': 'Alcance global com atendimento automatizado',
        'home.socialCommerceMadeEasy': 'Comércio social facilitado',
        'home.quickProductPublishingSalesTracking': 'Publicação rápida de produtos e acompanhamento de vendas',
        'home.brazilianMarketLeaderIntegration': 'Integração com líder do mercado brasileiro',
        // Badge texts
        'home.automated': 'Automatizado',
        'home.secure': 'Seguro',
        // Additional texts
        'home.signIn': 'Entrar',
        'home.getStartedFree': 'Começar Grátis',
        'home.perfectForGettingStarted': 'Perfeito para começar',
        'home.popular': 'Popular',
        'home.perMonth': 'por mês',
        'home.everythingYouNeedToSucceed': 'Tudo que você precisa para ter sucesso no dropshipping',
        'home.joinThousandsOfSuccessfulEntrepreneurs': 'Junte-se a milhares de empreendedores de sucesso que já estão usando nossa plataforma',
        'home.alreadyHaveAnAccount': 'Já tem uma conta?',
        // Additional marketplace and workflow text
        'home.automatedWorkflow': 'Fluxo de Trabalho Automatizado',
        'home.fromOrderReceivedToShipment': 'Do pedido recebido ao envio - totalmente automatizado em segundos sem erros',
        'home.automatedInRealTime': 'Automatizado em tempo real com zero intervenção manual. Nosso sistema inteligente gerencia tudo perfeitamente.',
        'home.lessThan2s': '< 2s',
        'home.successRate': '99,9% de Sucesso',
        'home.processingTime': '< 5s Tempo de Processamento',
        'home.accuracyRate': '99,9% Taxa de Precisão',
        'home.alwaysActive': '24/7 Sempre Ativo',
        'home.ordersProcessedInstantly': 'Pedidos processados instantaneamente com sincronização de estoque em tempo real em todos os marketplaces',
        'home.zeroManualWork': 'Zero trabalho manual - da captura do pedido à geração da fatura, tudo funciona automaticamente',
        'home.aiPoweredValidation': 'Validação alimentada por IA garante 99,9% de precisão com detecção e recuperação automática de erros',
        'home.trackEarningsManageTransactions': 'Acompanhe ganhos, gerencie transações e processe saques instantâneos - tudo em um lugar',
        'home.totalBalance': 'Saldo Total',
        'home.thisMonth': 'este mês',
        'home.paymentReceived': 'Pagamento Recebido',
        'home.order': 'Pedido',
        'home.today': 'Hoje',
        'home.yesterday': 'Ontem',
        'home.realTimeBalance': 'Saldo em tempo real',
        'home.realTimeRevenueTracking': 'Acompanhamento de receita em tempo real com análises detalhadas, relatórios automatizados e insights financeiros para ajudar você a crescer seu negócio.',
        'home.bankLevelEncryption': 'Criptografia de nível bancário, proteção contra fraudes e conformidade com padrões internacionais de segurança mantêm seu dinheiro seguro.',
        'home.accessFundsAnytime': 'Acesse seus fundos a qualquer momento com pagamentos automatizados. Integração com Mercado Pago, PIX e principais gateways de pagamento.',
        // Additional missing translations
        'home.hoverToPauseRotation': 'Passe o mouse para pausar a rotação',
        'home.marketplaceIntegration': 'Integração de Marketplace',
        'home.bankTransfer': 'Transferência Bancária',
        'home.withdrawal': 'Saque',
        'home.daysAgo': 'dias atrás',
        // Whitelabel Solution
        'home.completeWhitelabelSolution': 'Solução whitelabel completa com domínios personalizados, marca e escalabilidade ilimitada',
        'home.dropshipPlatform': 'Plataforma Dropship',
        'home.customColorScheme': 'Esquema de Cores Personalizado',
        'home.useYourOwnDomain': 'Use seu próprio nome de domínio e crie uma identidade de marca única que ressoa com seus clientes.',
        'home.customizeColorsLogos': 'Personalize cores, logotipos, fontes e layouts para corresponder perfeitamente à sua marca em todas as páginas.',
        'home.customersSeeOnlyYourBrand': 'Seus clientes veem apenas sua marca - sem branding de terceiros ou referências em qualquer lugar.',
        'home.growWithoutLimits': 'Cresça sem limites - adicione produtos, usuários e marketplaces ilimitados conforme você escala.',
        'home.customLogoFavicon': 'Logotipo personalizado e favicon',
        'home.customColorSchemes': 'Esquemas de cores personalizados',
        'home.customDomainSetup': 'Configuração de domínio personalizado',
        'home.emailTemplatesWithBranding': 'Modelos de email com branding',
        'home.fullyCustomizableYourBrandYourRules': '100% Personalizável • Sua Marca • Suas Regras',
        // Plans and Subscriptions
        'home.flexiblePricingPlans': 'Planos de preços flexíveis projetados para escalar com seu negócio de dropshipping',
        'home.activeSKUs': 'SKUs Ativos',
        'home.ordersPerMonth': 'Pedidos/mês',
        'home.marketplaces': 'Marketplaces',
        'home.basicSupport': 'Suporte Básico',
        'home.emailSupport': 'Suporte por Email',
        'home.basicReports': 'Relatórios Básicos',
        'home.prioritySupport': 'Suporte Prioritário',
        'home.advancedReports': 'Relatórios Avançados',
        'home.apiAccess': 'Acesso à API',
        'home.unlimitedSKUs': 'SKUs Ilimitados',
        'home.unlimitedOrders': 'Pedidos Ilimitados',
        'home.unlimitedMarketplaces': 'Marketplaces Ilimitados',
        'home.allMarketplaces': 'Todos os Marketplaces',
        'home.support24_7': 'Suporte 24/7',
        'home.customReports': 'Relatórios Personalizados',
        'home.dedicatedManager': 'Gerente Dedicado',
        'home.startFree': 'Começar Grátis',
        'home.startBasicPlan': 'Iniciar Plano Básico',
        'home.goPro': 'Tornar-se Pro',
        'home.contactSales': 'Falar com Vendas',
        'home.custom': 'Personalizado',
        // Payment Options
        'home.visaMastercardAmericanExpress': 'Visa, Mastercard, American Express',
        'home.instantBrazilianPayments': 'Pagamentos brasileiros instantâneos',
        'home.bankSlipPayments': 'Pagamentos por boleto',
        'home.automaticBilling': 'Cobrança automática',
        'home.retryOnFailure': 'Tentar novamente em caso de falha',
        'home.webhookIntegration': 'Integração de webhook',
        'home.autoUpgradeOptions': 'Opções de atualização automática',
        
        // Admin Dashboard
        'admin.welcomeBack': 'Bem-vindo de Volta',
        'admin.dashboard': 'Painel Administrativo',
        'admin.loadingDashboard': 'Carregando Painel Administrativo...',
        'admin.userManagement': 'Gerenciamento de Usuários',
        'admin.allUsers': 'Todos os Usuários',
        'admin.addNewUser': 'Adicionar Novo Usuário',
        'admin.searchUsers': 'Buscar usuários por nome ou email...',
        'admin.loadingUsers': 'Carregando Usuários...',
        'admin.backToAdmin': 'Voltar ao Painel Administrativo',
        'admin.enterFirstName': 'Digite o primeiro nome',
        'admin.enterLastName': 'Digite o sobrenome',
        'admin.enterEmail': 'Digite o endereço de email',
        'admin.enterPassword': 'Digite a senha',
        'admin.confirmPassword': 'Confirme a senha',
        'admin.permissions': 'Permissões',
        'admin.loadingPermissions': 'Carregando Permissões...',
        'admin.searchPermissions': 'Buscar permissões...',
        'admin.allCategories': 'Todas as Categorias',
        'admin.searchModules': 'Buscar módulos, fornecedores, pedidos...',
        'admin.searchSuppliers': 'Buscar fornecedores...',
        'admin.searchProducts': 'Buscar produtos...',
        
        // Admin Sidebar and Navigation
        'admin.controlPanel': 'Painel de Controle Administrativo',
        'admin.platformManagement': 'Gerenciamento da Plataforma',
        'admin.overview': 'Visão Geral',
        'admin.multiTenantSuppliers': 'Fornecedores Multi-Inquilino',
        'admin.supplierManagement': 'Gerenciamento de Fornecedores',
        'admin.productManagement': 'Gerenciamento de Produtos',
        'admin.orderManagement': 'Gerenciamento de Pedidos',
        'admin.financialManagement': 'Gerenciamento Financeiro',
        'admin.analytics': 'Análises',
        'admin.settings': 'Configurações',
        'admin.notifications': 'Notificações',
        'admin.recentActivity': 'Atividade Recente',
        'admin.quickActions': 'Ações Rápidas',
        'admin.systemSettings': 'Configurações do Sistema',
        
        // User Roles
        'admin.admins': 'Administradores',
        'admin.operators': 'Operadores',
        'admin.suppliers': 'Fornecedores',
        'admin.sellers': 'Vendedores',
        
        // Admin Descriptions
        'admin.manageAllUsers': 'Gerenciar todos os usuários da plataforma e suas permissões',
        'admin.configureRoleBasedAccess': 'Configurar permissões de controle de acesso baseado em funções',
        'admin.saveChanges': 'Salvar Alterações',
        
        // Admin Stats and Data
        'admin.totalSuppliers': 'Total de Fornecedores',
        'admin.activeSuppliers': 'Fornecedores Ativos',
        'admin.newSupplierOnboarded': 'Novo fornecedor "TechSupply Pro" integrado com sucesso',
        'admin.batchOrdersProcessed': 'Lote de 47 pedidos processado automaticamente',
        'admin.commissionPayoutCompleted': 'Pagamento de comissão de $12.450 concluído',
        'admin.lowInventoryAlert': 'Alerta de estoque baixo para 5 produtos',
        'admin.apiSyncCompleted': 'Sincronização da API Mercado Livre concluída',
        'admin.minAgo': 'min atrás',
        
        // Admin Categories
        'admin.financial': 'Financeiro',
        'admin.reportsAnalytics': 'Relatórios e Análises',
        'admin.allSuppliers': 'Todos os Fornecedores',
        
        // Admin Actions
        'admin.viewAnalytics': 'Ver Análises',
        'admin.viewFinancialData': 'Ver Dados Financeiros',
        'admin.viewSettings': 'Ver Configurações',
        'admin.editSettings': 'Editar Configurações',
        'admin.configureSettings': 'Configurar Configurações',
        // Key Benefits
        'home.connectWithMultipleMarketplacesSellEverywhere': 'Conecte-se com múltiplos marketplaces e venda em todos os lugares',
        'home.focusOnGrowingBusinessHandleLogistics': 'Concentre-se em expandir seu negócio enquanto cuidamos da logística',
        'home.runYourOwnBrandedPlatformScalability': 'Execute sua própria plataforma de marca para escalabilidade',
        'home.seamlessFinancialTransactionsIntegratedGateways': 'Transações financeiras perfeitas com gateways de pagamento integrados',
        'home.alwaysUpToDateAcrossAllPlatforms': 'Sempre atualizado, em todas as plataformas',
        // Footer
        'home.dropshipHubForMe': 'Dropship Hub Para Mim',
        'home.dropshipHubForBusiness': 'Dropship Hub Para Negócios',
        'home.howItWorks': 'Como Funciona',
        'home.pricingAndPlans': 'Preços e Planos',
        'home.faqs': 'FAQs',
        'home.shippingMethods': 'Métodos de Envio',
        'home.whatCanISell': 'O Que Posso Vender?',
        'home.whatIsDropshipHub': 'O Que É Dropship Hub',
        'home.warehouseLocations': 'Localizações de Armazém',
        'home.blog': 'Blog',
        'home.news': 'Notícias',
        'home.customerReviews': 'Avaliações de Clientes',
        'home.affiliateProgram': 'Programa de Afiliados',
        'home.directSellers': 'Vendedores Diretos',
        'home.usUnlocked': 'EUA Desbloqueado',
        'home.contactUsLink': 'Fale Conosco',
        'home.liveChatPST': 'Chat ao vivo (Fuso Horário PST):',
        'home.weekdaysHours': 'Dias de semana: 9h às 17h',
        'home.weekendsClosed': 'Fins de semana: Fechado',
        // CTA Section
        'home.noCreditCardRequired': 'Nenhum cartão de crédito necessário',
        'home.freeForeverPlan': 'Plano gratuito para sempre',
        'home.setupIn5Minutes': 'Configuração em 5 minutos',
        // Additional missing translations
        'home.multiChannelIntegration': 'Integração Multi-Canal',
        'home.automatedOrderFulfillment': 'Atendimento Automatizado de Pedidos',
        'home.whitelabelSolution': 'Solução White Label',
        'home.digitalWallet': 'Carteira Digital',
        'home.realTimeDataSyncing': 'Sincronização de Dados em Tempo Real',
        'home.mercadoPago': 'Mercado Pago',
        'home.creditCard': 'Cartão de Crédito',
        'home.allRightsReserved': 'Todos os direitos reservados',
        'home.privacyPolicy': 'Política de Privacidade',
        'home.termsOfService': 'Termos de Serviço',
        'home.signUpNowItsFree': 'Cadastre-se Agora - É Grátis!'
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('pt'); // Default to Brazilian Portuguese
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    // Set client flag
    setIsClient(true);
    
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('preferred-language');
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'pt')) {
      setCurrentLanguage(savedLanguage);
    } else {
      // Set default to Brazilian Portuguese if no saved language
      setCurrentLanguage('pt');
      localStorage.setItem('preferred-language', 'pt');
    }
  }, []);

  const changeLanguage = (language: string) => {
    if (!isClient) return;
    setCurrentLanguage(language);
    localStorage.setItem('preferred-language', language);
  };

  const t = (key: string): string => {
    // Fallback for server-side rendering
    if (!isClient) {
      return translations.en[key as keyof typeof translations.en] || key;
    }
    
    const currentTranslations = translations[currentLanguage as keyof typeof translations];
    const result = currentTranslations[key as keyof typeof currentTranslations] || key;
    
    
    return result;
  };

  const isRTL = currentLanguage === 'ar'; // Arabic support for future

  const value: LanguageContextType = {
    currentLanguage,
    changeLanguage,
    t,
    isRTL
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};